# Generated by Django 5.2.6 on 2025-09-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('store', models.IntegerField(blank=True, db_column='store_id', null=True)),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'indexes': [models.Index(fields=['username'], name='staff_staff_usernam_b3af0e_idx'), models.Index(fields=['email'], name='staff_staff_email_87de38_idx'), models.Index(fields=['phone'], name='staff_staff_phone_820983_idx'), models.Index(fields=['active'], name='staff_staff_active_c7312e_idx')],
            },
        ),
    ]
