# Generated by Django 4.2.7 on 2025-10-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='staff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Staff Token',
                'verbose_name_plural': 'Staff Tokens',
            },
        ),
    ]
