# Generated by Django 4.2.7 on 2025-10-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock'),
        ('staff', '0004_remove_staff_store_staff_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='store.store'),
        ),
    ]
