# Generated by Django 4.2.7 on 2025-10-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_store_id_staff_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.AddField(
            model_name='staff',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
