# Generated by Django 4.2.7 on 2025-10-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='The name of the store', max_length=255, verbose_name='store name')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the store', max_length=25, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, help_text='Contact email for the store', max_length=255, null=True, verbose_name='email address')),
                ('street', models.CharField(blank=True, help_text='Street address of the store', max_length=255, null=True, verbose_name='street address')),
                ('city', models.CharField(blank=True, help_text='City where the store is located', max_length=255, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, help_text='State/Province/Region code', max_length=10, null=True, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, help_text='Postal/ZIP code of the store location', max_length=5, null=True, verbose_name='zip code')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the store record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the store record was last updated', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'db_table': 'sales.stores',
                'ordering': ['store_name'],
            },
        ),
    ]
