# Generated by Django 4.2.7 on 2025-10-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in stock', verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the stock record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the stock record was last updated', verbose_name='updated at')),
                ('product', models.ForeignKey(help_text='The product in stock', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product')),
                ('store', models.ForeignKey(help_text='The store where this stock is located', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.store')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'inventory.stocks',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
