# Generated by Django 4.2.7 on 2025-10-10 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('model_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brand.brand')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['product_name'], name='product_pro_product_5af997_idx'), models.Index(fields=['brand_id'], name='product_pro_brand_i_5d76ed_idx'), models.Index(fields=['category'], name='product_pro_categor_2b9d78_idx'), models.Index(fields=['deleted_at'], name='product_pro_deleted_f941f6_idx')],
            },
        ),
    ]
